name: CI Build

on: [push, pull_request]

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1.0.3
  build:
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Protos
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: assemble
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          dependencies-cache-key: gradle/dependency-locks/**
          dependencies-cache-exact: true
          configuration-cache-enabled: true
          configuration-cache-key: gradle/dependency-locks/**
          configuration-cache-exact: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload envoy-api-kotlin Jar
        uses: actions/upload-artifact@v2.2.1
        with:
          name: envoy-api-kotlin
          path: build/libs/
          if-no-files-found: error
      - name: Publish Maven package
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: publish
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          dependencies-cache-key: gradle/dependency-locks/**
          dependencies-cache-exact: true
          configuration-cache-enabled: true
          configuration-cache-key: gradle/dependency-locks/**
          configuration-cache-exact: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}
